### ISSUE TITLE
Créer un repo Saleor avec la version stable 3.20.8

### ISSUE THREAD

**Issue by zlorgoncho1** [DSsenegal/saleor#1]
Hello @zlorgoncho1 
L'idée est de partie d'une version stable, la dernier est la [3.20.8](https://github.com/saleor/saleor/releases/tag/3.20.8)

```shell
git clone --branch 3.20.8 --single-branch https://github.com/saleor/saleor.git
```

J'ai try un import des fichiers https://github.com/saleor/saleor/archive/refs/tags/3.20.8.zip pour créer le repo

![Image](https://github.com/user-attachments/assets/f8cae27b-f1ce-4b49-a603-a375b9ad2db4)

sa ne marche pas

![Image](https://github.com/user-attachments/assets/c13d034d-1c3a-4982-822b-7b3cb3676844)

Je te laisse le faire manuellement

**Comment by zlorgoncho1** [comment]
Hello @dofbi, bien reçu.

**Comment by zlorgoncho1** [comment]
Hello @dofbi, j'ai crée le repository sur la base de la version 3.20.8 . Voici la série de commande que j'ai utilisé, ça peut servir à quelqu'un.

```sh
git checkout tags/3.20.8 # Permet de se position sur le tag
git switch -c dscale # Créer une branche à partir de du tag
git remote add dscale https://github.com/DSsenegal/saleor.git # Ajouter le nouveau repo distant
git push -u dscale main # Envoyer la branche au repo distant en tant que main.
```


Voici un aperçu du repo:

![Image](https://github.com/user-attachments/assets/1cb5ace6-5f55-43df-8333-073b669ef2ac)

**Comment by dofbi** [comment]
Merci @zlorgoncho1 pour la doc 🎉

**Comment by dofbi** [comment]
Question @zlorgoncho1 
Pourquoi nous avons les autres branches dans le repo ?



![Image](https://github.com/user-attachments/assets/4280dd8a-6e54-486e-a239-eec69945a00a)

**Comment by zlorgoncho1** [comment]
J'ai commit directement depuis le repo saleor, ils s'agissent sans doute de branches rattachés aux tag de la version. Je peux supprimer toutes ces branches et laisser que main.

**Comment by dofbi** [comment]
N'hésite pas à refaire le process sur ton repo pour vérifier, si ces des branches rattachés alors tu peux supprimer
Merci @zlorgoncho1

**Comment by zlorgoncho1** [comment]
Hello @dofbi , j'ai refait le processus, en effet le script ne push que la branche qui a été définie, il ne s'agit pas de branches qui lui sont rattachées. Mais ces branches sont créé par `dependantbot` lors de l'execution des githubs actions.
