### ISSUE TITLE
Déploiement de l'écosystème saleor

### ISSUE THREAD

**Issue by zlorgoncho1** [DSsenegal/saleor#15]
Création des repositories:
- [x] Core
- [x] Dashboard

Déploiement:
- [x] [Saleor](https://github.com/dssenegal/saleor)
- [x] [saleor dashboard](https://github.com/dssenegal/saleor-dashboard)

**Comment by dofbi** [comment]
Hello @honorableCon 
Je te propose de regarder [saleor dashboard](https://github.com/dssenegal/saleor-dashboard) 🙏

**Comment by honorableCon** [comment]
D'accord @dofbi je l'avais déjà forké même 🚀

**Comment by zlorgoncho1** [comment]
Hello @dofbi, finalement l'approche du virtualenv m'a beaucoup aidé. Nous avons ce script qui nous permet de déployer le core.

```bash
#!/bin/bash
sudo apt-get update
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt-get update
sudo apt install -y python3.9 python3.9-venv python3.9-dev
sudo apt-get install -y libcairo2 libgdk-pixbuf2.0-0 liblcms2-2 libopenjp2-7 libpango-1.0-0 libpangocairo-1.0-0 libssl3 libwebp7 libxml2 libpq5 shared-mime-info mime-support
sudo apt-get install -y libpq-dev build-essential
pip install psycopg2-binary
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python3.9 get-pip.py
python3.9 -m venv env
source env/bin/activate
pip install poetry==1.7.0
poetry config virtualenvs.create false
git clone https://github.com/DSsenegal/saleor.git
cd saleor/
poetry install --no-root
echo 'image/webp webp' | sudo tee -a /etc/mime.types
echo 'image/avif avif' | sudo tee -a /etc/mime.types
mkdir media
mkdir static
SECRET_KEY=saleor STATIC_URL=0.0.0.0:8000/static/ python3 manage.py collectstatic --no-input
SECRET_KEY=saleor STATIC_URL=0.0.0.0:8000/static/ python3 manage.py runserver
```

**Comment by zlorgoncho1** [comment]
Je vais maintenant essayer de déployer la base de donnée sur le même server, (défaut de ressources).

![Image](https://github.com/user-attachments/assets/861b6c82-8c81-4ef3-a3d9-73e867f86fad)

**Comment by zlorgoncho1** [comment]
Hello @dofbi , j'ai installé le postgres, voici les différents steps:

```bash
# Installation de postgres
sudo apt update
sudo apt install -y wget gnupg2
wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
sudo apt update
sudo apt install -y postgresql-15
sudo systemctl start postgresql
sudo systemctl enable postgresql
sudo -i -u postgres

sudo -i -u postgres
psql
```
```sql
CREATE USER saleor WITH PASSWORD 'saleor';
ALTER USER saleor WITH SUPERUSER;

CREATE DATABASE saleor;
```
```bash
\q
exit
```

**Comment by zlorgoncho1** [comment]
Hello @dofbi, maintenant il faut juste effectuer les migrations et puis lancer le server:

```bash
SECRET_KEY=saleor STATIC_URL=0.0.0.0:8000/static/ python3 manage.py makemigrations
SECRET_KEY=saleor STATIC_URL=0.0.0.0:8000/static/ python3 manage.py migrate
SECRET_KEY=saleor STATIC_URL=0.0.0.0:8000/static/ python3 manage.py runserver
```

![Image](https://github.com/user-attachments/assets/fb721886-5526-44b1-8b16-15ba112cdfe4)

L'api est up

**Comment by dofbi** [comment]
Good job @zlorgoncho1 
Une adresse url ?

**Comment by zlorgoncho1** [comment]
Je configure les permissions côté AWS.

**Comment by zlorgoncho1** [comment]
Hello @dofbi, voici le lien:
http://ec2-3-68-84-60.eu-central-1.compute.amazonaws.com/graphql/

![Image](https://github.com/user-attachments/assets/892937a3-f080-44d4-8afb-df544e8f3a98)

**Comment by dofbi** [comment]
Hello @zlorgoncho1 
- postgres ✅️❓️
- Installation Dasbord ✅️❓️

**Comment by zlorgoncho1** [comment]
Hello @dofbi , l'install du postgres est bon depuis la mise en place du core. L'installation du dashboard, pas encore, le server crash a chaque build. Je builds sur ma machine local pour le copier sur le server.

**Comment by zlorgoncho1** [comment]
Hello @dofbi ,
Je viens de déployer le Dashboard. Il est disponible a l'Endpoint suivant:
http://ec2-3-68-84-60.eu-central-1.compute.amazonaws.com/

Le core est a l'Endpoint suivant:
http://ec2-3-68-84-60.eu-central-1.compute.amazonaws.com:8000/graphql/

Ils sont indépendants de la session, autrement disponible même quand je me déconnecte du ssh.

**Comment by dofbi** [comment]
Hello @zlorgoncho1 
Pour le Dashboard, pas besoin de l'avoir dans la même machine, nous pouvons l'avoir sur un vercel, netlify ou autre.

Pour la machine core, la migration passe ?

**Comment by zlorgoncho1** [comment]
Hello @dofbi,
Pour la machine core la migration passe. Voici les taches a faire:
- [ ] Dissocier le core du dashboard et deployer le dashboard su vercel ou netlify.
- [x] Deployer la base de donnee en aws native.

**Comment by zlorgoncho1** [comment]
Hello @dofbi ,

Lorsque j'essaie de build sur vercel, il faudra y'a une erreur comme quoi y'a pas assez de mémoire.

![Image](https://github.com/user-attachments/assets/332e7e51-5380-4fba-8af1-cfe5ddb73396)

**Comment by dofbi** [comment]
Try avec netlify @zlorgoncho1

**Comment by zlorgoncho1** [comment]
@dofbi , avec Netlify, on a aussi un soucis :

![Image](https://github.com/user-attachments/assets/ab7e7b92-e56c-4412-9be7-f30106bc6b98)

**Comment by dofbi** [comment]
Hello @zlorgoncho1 
Je te propose de faire le build sur github avec les actions puis d'envoyer les fichier statics

Voici une action qui automatise cela

https://github.com/marketplace/actions/netlify-deploy

**Comment by zlorgoncho1** [comment]
Hello @dofbi , Pour la base de donnée, c'est crée sur AWS. Je le plug au projet.

![Image](https://github.com/user-attachments/assets/8f640d2c-4c83-4de4-8a66-b19ab50aeacd)

**Comment by zlorgoncho1** [comment]
Hello @dofbi , je rencontre ce soucis avec la connexion de la base de donnée sur aws, quand j'essaie la migration:

![Image](https://github.com/user-attachments/assets/bc95658c-0c13-41f1-a8fa-c31be083806d)

**Comment by dofbi** [comment]
Hello @zlorgoncho1 merci de patager ta configuration sur une branche

**Comment by zlorgoncho1** [comment]
Hello @dofbi , Voici les actions qui ont ete effectue:

- [x] Creation de la base de donne sur AWS avec les RDS
- [x] Deploiement du core multi tenant suivant la branche django-tenantt-schema-2
- [x] Deploiement du premier front dans le server: https://dscale-saleor-dashboard.netlify.app/

**Comment by dofbi** [comment]
Hello @zlorgoncho1 
Good job
- Quel est la nouvelle adresse du saleor core
- Et pour le login quel est le user par défaut

**Comment by zlorgoncho1** [comment]
Voici l'adresse du dashboard-1: https://dscale-saleor-dashboard.netlify.app/
Voici l'adresse du dashboard-2: https://dscale-saleor-dashboard-2.netlify.app/

L'adresse du core n'a pas change: http://ec2-3-68-84-60.eu-central-1.compute.amazonaws.com:8000/graphql/

C'est juste que par soucis de ressource, le server crash. Je précise que la base de donnée est retirée, mais aussi les Dashboards.

Pour le login, on a toujours pas pu créer un utilisateur a cause du server qui crash a chaque 2 requêtes.

**Comment by dofbi** [comment]
@zlorgoncho1 
- Update [HOST](https://github.com/DSsenegal/.github-private/blob/main/HOST.md) avec les nouvelles adresse.
- sinon c'est quoi la config de la machine et ces ressources.
- quel sont les recommendations de saleor

**Comment by zlorgoncho1** [comment]
J'ai etendu les specs de la machine pour pouvoir faire les configuration correctement. On est alors passe de 1 vcpu, 1 Go Ram a 4vcpu, 8Go Ram, ca tourne normalement.

Voici le nouveau Host: http://ec2-3-70-156-20.eu-central-1.compute.amazonaws.com:8000/graphql/


2 schemas ont ete cree:

shop1 et shop2, je vous envoie lese informations de la base de donnee sur discord.

**Comment by zlorgoncho1** [comment]
Hello @dofbi , @honorableCon , @mass-gueye ,

Nous avons déployé un troisième dashboard. Les deux premiers dashboards ne fonctionnaient pas à cause du HTTPS. Les sites en HTTPS ne peuvent pas faire de requêtes vers des sites en HTTP (les requêtes sont bloquées au niveau du client). Deux options s'offraient à nous :

Déployer les frontends sur un provider qui supporte le HTTP, ce qui n'est pas le cas de Netlify.
Rendre les backends disponibles en HTTPS, ce qui n'est pas possible pour le moment, car notre DNS est fourni par AWS, et nous n'avons pas accès aux enregistrements pour générer notre propre certificat avec Let's Encrypt.
Finalement, j'ai redéployé le frontend sur notre serveur AWS en HTTP, levant ainsi la première limitation. Il restait un autre problème lié au CORS. Nous avons donc ajouté un package CORS pour gérer ces limitations.

À cette heure, nous avons un troisième dashboard disponible à l'adresse suivante : [Dashboard](http://ec2-3-70-156-20.eu-central-1.compute.amazonaws.com/)

L'utilisateur admin par défaut est :

```sh
email: admin@example.com
password: admin
```

Vous trouverez la branche `deploy-static`, qui correspond a la branche déployée avec les configs.
