### ISSUE TITLE
Tenant Feature

### ISSUE THREAD

**Issue by dofbi** [DSsenegal/saleor#19]
### Voici les champs à ajouter sur le tenant (minimum)

```ts
interface Tenant {
  id: string;
  domainUrl: string;
  createdAt: string;
  name: string;
  description: string;
  adminEmail: string;
  adminPhone: string;
  isApproved: boolean;
}
```

### Qraphql Queries

- [x] get all tenants
- [x] get tenant with ID

### Graphql Mutations
- [x] create tenant (as superadmin)
- [x] create tenant draft (as user)
- [x] approve tenant (as superadmin)

### UI interface
- [ ] superadmin dashboard to manage tenant
- [ ] sign interface for superadmin
- [ ] tenant creation form

**Comment by dofbi** [comment]
Hello @honorableCon 
Tu travail sur quel branche

**Comment by dofbi** [comment]
hello @zlorgoncho1 
Quel est la dernière branche déployer  sur le serveur ?

**Comment by honorableCon** [comment]
j'ai pris la branche main comme base

**Comment by zlorgoncho1** [comment]
Hello @dofbi , la branche déployée est la branche `deploy-static` comme précise sur cet issue:
[Saleor issue 15](https://github.com/DSsenegal/saleor/issues/15#issuecomment-2295491929)

**Comment by honorableCon** [comment]
@dofbi you can review the linked branch :

- [x] tenants : to get all tenants
- [x] tenant : to get tenant with ID
- [x] tenantCreate : to create tenant
- [x] tenantDraftCreate : to create a draft (for client)
- [x] tenantApprove : to approve approve draft and create tenant

## Missings
- permission to create and approve tenant have to be restricted to admin

**Comment by dofbi** [comment]
@honorableCon Super !  
Je te recommande d’ouvrir dès maintenant la PR pour préparer le déploiement avec @zlorgoncho1. Ensuite, tu pourras continuer tranquillement le reste.  
Bon travail !
