### ISSUE TITLE
Deploiement du Saleor Core Multi Tenant sur DigitalOcean

### ISSUE THREAD

**Issue by zlorgoncho1** [DSsenegal/saleor#23]
Hello @dofbi , je vais déployer la version stable du multi tenant sur Digital Ocean, en utilisant les `droplets`. D'apres @honorableCon, il s'agit de la branche `multi-tenancy`.

**Comment by dofbi** [comment]
Hello @zlorgoncho1 
déploiement 🆗 ?

**Comment by zlorgoncho1** [comment]
Hello @dofbi. C'est en cours ...

**Comment by zlorgoncho1** [comment]
- [x] Creation du server (droplet)
- [x] Deploiement de la base de donnee
- [ ] Installation des dependances
- [ ] Deploiement du core

**Comment by zlorgoncho1** [comment]
Hello @dofbi , la base de donnee est deployee. @honorableCon tu peux essayer de te connecter avec ton pgadmin:
- User: `saleor`
- Password: `****`
- Database: ``
- Host: `xx.xx.xx.xx`
- Port: `5432`

**Comment by zlorgoncho1** [comment]
Hello @dofbi , @honorableCon , je rencontre cette erreur lors du demarrage de l'application:

![Image](https://github.com/user-attachments/assets/44cad90b-8d8f-41a9-b3ff-da2c6f094b2f)

**Comment by zlorgoncho1** [comment]
J'ai pu fix, au lieu d'utiliser `... manage.py runserver`, j'ai utilisé `poetry run uvicorn saleor.asgi:application --reload`.

**Comment by honorableCon** [comment]
comment tu l'as démarré ?

**Comment by honorableCon** [comment]
okay c'est comme ça : poetry run uvicorn saleor.asgi:application --reload
qu'on le démarre

**Comment by zlorgoncho1** [comment]
Merci @honorableCon !
Hello @dofbi, l'app est deploye mais on ne peut pas y acceder depuis l'adresse ip public. J'ai verifie les config firewall cote Digital Ocean

![Image](https://github.com/user-attachments/assets/e403bf73-7da2-4e81-b3fc-d0b315000865)

 De meme que pour le pare-feu ufw:

![Image](https://github.com/user-attachments/assets/9d13c449-6b47-425d-b12d-5a916e714bb8)

Et pourtant on voit bien que l'app repond:

![Image](https://github.com/user-attachments/assets/d799e95e-9e3f-4e45-ab75-e43a7f80a732)

![Image](https://github.com/user-attachments/assets/7cee231d-26b4-4dfd-9dfc-54d4fcd31b4b)

**Comment by dofbi** [comment]
Hello @zlorgoncho1 
Good job, une bonne nuit de sommeil pour trouver une solution d'ici demain 🙏🏾

**Comment by zlorgoncho1** [comment]
Hello @dofbi , @honorableCon , @mass-gueye , finalement, j'ai pu fix l'erreur en rajoutant les paramètres `--host 0.0.0.0 --port 8000` a la commande poetry de démarrage du server. Et bonne nouvelle, les tenants marchent correctement !

Voici une capture d'écran de shop 1:
![Image](https://github.com/user-attachments/assets/adf290df-c88e-4ec0-afc5-78744a350f37)

Voici une capture d'écran de shop 2:
![Image](https://github.com/user-attachments/assets/c0fb2445-0ed6-49ff-bdc2-e295477edb24)

Vous pouvez tester de vos cotes en rajoutant ces lignes au niveau des fichiers hosts de vos OS:

```
157.230.78.219 shop1.saleor-multi-tenant.io
157.230.78.219 shop2.saleor-multi-tenant.io
157.230.78.219 saleor-multi-tenant.io
```

Je vais essayer d'alimenter les deux shop avec la commande. Je vous tiens au courant !

**Comment by dofbi** [comment]
Nie work @zlorgoncho1 👏🏾 👏🏾 👏🏾

**Comment by zlorgoncho1** [comment]
Hello @dofbi , j'ai pu populate la base de donnee pour les 3 schemas, shop1, shop2, shop3.

![Image](https://github.com/user-attachments/assets/a8c2f800-5deb-41b6-8cb3-b3fa28689bab)


Actuellement le soucis qui se pose, c'est qu'on ne peut que se connecter avec le schemas public et non les autres.

**Comment by zlorgoncho1** [comment]
En réalité, le login pointe toujours vers le public. Et cela est bloquant, si on déploie les Dashboard, on ne pourra pas se connecter.

**Comment by zlorgoncho1** [comment]
Hello @dofbi , @honorableCon , @mass-gueye , finalement j'ai pu fix l'erreur d'authentification.
Le soucis etait que parfois pour certaines requetes, le multi-tenant etait bypasser et on se retrouve avec un object FakeTenant a la place de Tenant comme vous pouvez le voir ici:

![Image](https://github.com/user-attachments/assets/482b8690-5d8b-4fb2-967e-7bfaf7cb9932)

Il m'a fallu alors en plus du middleware que @honorableCon avait creer, de rajouter explicitement ce middleware (`"django_tenants.middleware.TenantMiddleware"`) et a la premiere position dans la liste. Ce qui fera executer le middleware avant les autres et forcer entre autre le tenant.

Apres avoir effectue le changement, les logins se sont bien passes en respectant les tenants.
 
![Image](https://github.com/user-attachments/assets/5938180b-30b8-417b-9d43-c8ca2eb01522)

![Image](https://github.com/user-attachments/assets/fd5bfc66-43f1-4864-b5de-3b3ce7b70500)

![Image](https://github.com/user-attachments/assets/faa56003-b5fb-40f5-b170-f08459e56ac0)

Je vais me reposer et demain inchallah, je vais essayer de deployer deux dashboard pour avoir une vision beaucoup plus parlant avec les multi-tenants.

**Comment by honorableCon** [comment]
Waa saleor niooko tayy je pense 😂
Good job 👏 @zlorgoncho1
